### ISSUE TITLE
When using with fresh install auth token errors

### ISSUE THREAD

**Issue by tthomas0702** [tthomas0702/bigiq-setup#8]
This is the error I am getting:

 ./setup-bigiq.py -a 10.3.214.15 -n bigiq-setup1.hiep.piv -R 10.3.254.254 -r big_iq -m 10.3.214.15/16 -s 10.1.214.15/16 -k Big-iq12345678910 -P f5site -cr root -nr f5site -p admin
[tthomas@vopti bigiq-setup]$ ./setup-bigiq.py -a 10.3.214.15 -n bigiq-setup1.hiep.piv -R 10.3.254.254 -r big_iq -m 10.3.214.15/16 -s 10.1.214.15/16 -k Big-iq12345678910 -P f5site -cr root -nr f5site -p admin
{'code': 400, 'message': 'No login provider named tmos.', 'originalRequestBody': '{"username":"admin","loginProviderName":"tmos","generation":0,"lastUpdateMicros":0}', 'restOperationId': 85416, 'errorStack': [], 'kind': ':resterrorresponse'}
Traceback (most recent call last):
  File "./setup-bigiq.py", line 304, in <module>
    auth_token = get_auth_token(opt.username, opt.password, opt.address)
  File "./setup-bigiq.py", line 224, in get_auth_token
    token = data_dict['token']['token']
KeyError: 'token'

for some reason "loginProviderName":"tmos" causes an error on a fresh install but worked on older versions and upgraded version even if clear-rest-storage was run.

**Comment by tthomas0702** [comment]
Fixed by removing 'loginProviderName': from POST to auth token. It is not needed. It will default to local when not included.
